export const env = {
  serverBaseUrl: process.env.SERVER_BASE_URL ?? 'http://localhost',
  port: process.env.PORT ?? '5000',
  cookieSecret: process.env.COOKIE_SECRET,
  cookieMaxAge: process.env.COOKIE_MAX_AGE ?? '1209600',
  clientBaseUrl: process.env.CLIENT_BASE_URL,
  dbSqliteFile: process.env.DB_SQLITE_FILE ?? 'data/db.sqlite',
  adminEmail: process.env.ADMIN_EMAIL,
  adminPassword: process.env.ADMIN_PASSWORD,
  mailerService: process.env.MAILER_SERVICE ?? 'gmail',
  mailerHost: process.env.MAILER_HOST ?? 'smtp.gmail.com',
  mailerPort: process.env.MAILER_PORT ?? '465',
  mailerSecure: process.env.MAILER_SECURE ?? 'true',
  mailerName: process.env.MAILER_NAME ?? 'Plant Care Diary',
  mailerUser: process.env.MAILER_USER,
  mailerPass: process.env.MAILER_PASS,
  jwtAccessSecret: process.env.ACCESS_TOKEN_SECRET,
  jwtRefreshSecret: process.env.REFRESH_TOKEN_SECRET,
  jwtAccessExpiration: process.env.ACCESS_TOKEN_EXPIRATION ?? '900',
  jwtRefreshExpiration: process.env.REFRESH_TOKEN_EXPIRATION ?? '1209600',
  ngrokAuthToken: process.env.NGROK_AUTHTOKEN ?? '',
  ngrokDomain: process.env.NGROK_DOMAIN ?? '',
  redisUrl: process.env.REDIS_URL ?? 'redis://localhost:6379',
}
